export const TERM_ACCENT = "74,222,128";

export const COMMANDS = {
  help: [
    "┌─────────────────────────────────────────┐",
    "│          AVAILABLE COMMANDS             │",
    "├─────────────────────────────────────────┤",
    "│  whoami     →  Who is Vardhan?          │",
    "│  skills     →  Tech stack & levels      │",
    "│  projects   →  All projects + links     │",
    "│  hire       →  Why work with me?        │",
    "│  contact    →  Get in touch             │",
    "│  status     →  Current availability     │",
    "│  vish       →  About Vish.AI            │",
    "│  vibeboard  →  About VibeBoard          │",
    "│  taskflow   →  About TaskFlow           │",
    "│  clear      →  Clear terminal           │",
    "└─────────────────────────────────────────┘",
  ],
  whoami: [
    "▸ NAME      : Vardhan Doharey",
    "▸ CLASS     : Full Stack Developer",
    "▸ SUBCLASS  : AI Enthusiast · Problem Solver",
    "▸ LEVEL     : 22",
    "▸ LOCATION  : Lucknow, Uttar Pradesh, India",
    "▸ STATUS    : Open to Work · Fresher",
    "",
    "I build real, live web apps with React, Next.js,",
    "Node.js, MongoDB, and Groq AI integrations.",
    "",
    "Shipped 4 projects including 2 live AI apps —",
    "Vish.AI (AI resume analyzer) and VibeBoard.",
    "",
    "I learn fast, ship things, and care deeply about quality.",
  ],
  skills: [
    "┌─ SKILL TREE ─────────────────────────────┐",
    "│  FRONTEND",
    "│  ▸ React / Next.js    ████████░░  85%",
    "│  ▸ Tailwind CSS       █████████░  90%",
    "│  ▸ HTML5 / CSS3       █████████░  92%",
    "│",
    "│  BACKEND",
    "│  ▸ Node.js / Express  ███████░░░  75%",
    "│  ▸ MongoDB            ███████░░░  70%",
    "│  ▸ REST APIs          ████████░░  80%",
    "│",
    "│  AI / TOOLS",
    "│  ▸ Groq AI / LLMs     ███████░░░  72%",
    "│  ▸ Git / Vercel       ████████░░  85%",
    "└──────────────────────────────────────────┘",
  ],
  projects: [
    "▸ [01] Vish.AI         — AI Resume Analyzer (Groq + Next.js)",
    "▸ [02] VibeBoard       — Mood to Aesthetic Universe (AI + Unsplash)",
    "▸ [03] TaskFlow        — Full Stack Task Manager (MERN + JWT)",
    "▸ [04] This Portfolio  — RPG-themed Next.js Portfolio",
    "",
    "Type [ vish ] [ vibeboard ] [ taskflow ] for deep dives.",
  ],
  vish: [
    "▸ PROJECT  : Vish.AI — AI Resume Analyzer",
    "▸ STACK    : Next.js · Groq Llama 3.3 70B · React · Node.js",
    "",
    "→ Paste resume or upload PDF",
    "→ Get ATS score out of 100",
    "→ Section breakdown + keyword gaps",
    "→ Actionable improvement suggestions",
    "→ Sub 3s response via Groq API",
    "",
    "Live → my-portfolio-lemon-nine-24.vercel.app/vish-ai",
  ],
  vibeboard: [
    "▸ PROJECT  : VibeBoard — Mood to Aesthetic Universe",
    "▸ STACK    : Next.js · Groq AI · Tailwind · Unsplash API",
    "",
    "→ Type your mood → get a full aesthetic universe",
    "→ AI color palette, anime match, music vibe",
    "→ Hinglish mood quote + dynamic Unsplash images",
    "",
    "Live → vibeboard-woad.vercel.app",
  ],
  taskflow: [
    "▸ PROJECT  : TaskFlow — Full Stack Task Manager",
    "▸ STACK    : MongoDB · Express.js · Next.js · Tailwind · JWT",
    "",
    "→ Full user authentication (JWT)",
    "→ Create, read, update, delete tasks",
    "→ Priority tagging (High / Medium / Low)",
    "→ Persistent data with MongoDB Atlas",
    "",
    "Live → taskflow-sand-gamma.vercel.app",
  ],
  hire: [
    "╔═══════════════════════════════════════════╗",
    "║         WHY WORK WITH VARDHAN?            ║",
    "╠═══════════════════════════════════════════╣",
    "║  ✓ Ships real live apps — not tutorials   ║",
    "║  ✓ 2 live AI apps using Groq + LLMs       ║",
    "║  ✓ Full Stack: Frontend → DB → Deploy     ║",
    "║  ✓ Fast learner — entire portfolio        ║",
    "║    built in under 2 months                ║",
    "║  ✓ Freelance · Full-time · Contract       ║",
    "╠═══════════════════════════════════════════╣",
    "║  Type [ contact ] to get in touch.        ║",
    "╚═══════════════════════════════════════════╝",
  ],
  contact: [
    "▸ EMAIL     : vardhandoharey@gmail.com",
    "▸ LINKEDIN  : linkedin.com/in/vardhan-doharey-zomb",
    "▸ GITHUB    : github.com/VishnuVardhan2000",
    "▸ PORTFOLIO : vardhan.is-a.dev",
    "",
    "Fastest response: LinkedIn DM or Email.",
    "I typically reply within 24 hours.",
  ],
  status: [
    "▸ AVAILABILITY   : Open to Work ✓",
    "▸ TYPE           : Full-time · Freelance · Contract",
    "▸ LOCATION       : Lucknow (Remote preferred)",
    "▸ NOTICE PERIOD  : Immediate",
    "▸ LAST SHIPPED   : Vish.AI (AI Resume Analyzer)",
    "",
    "→ Type [ hire ] to see why you should work with me.",
  ],
};

export const NOT_FOUND = (cmd) => [
  `command not found: ${cmd}`,
  "Type [ help ] to see all available commands.",
];

export const CHIP_COMMANDS = [
  "whoami","skills","projects","hire",
  "contact","status","vish","vibeboard","taskflow",
];